[package]
name = "hll"
version = "0.1.0"
authors = ["benl"]
edition = "2018"

[dev-dependencies]
rand = "0.8"
quickcheck = {version = "1.0.3", default_features = false, features = ["use_logging"]}
quickcheck_macros = "1"
